Fix locale format checking step

diff --git a/.github/workflows/add-locale.yml b/.github/workflows/add-locale.yml
--- a/.github/workflows/add-locale.yml
+++ b/.github/workflows/add-locale.yml
@@ -20,8 +20,8 @@ jobs:
 
       - name: Check locale format
         run: |
-          if! echo "$LOCALE" | grep -qE "^[a-z]{2}-[A-Z]{2}$"; then
-            echo "Error: Locale '$LOCALE' does not match the required format [a-z]{2}-[A-Z]{2}"
+          if ! grep -qE "^[a-z]{2}-[A-Z]{2}$" <<< "${{ github.event.inputs.locale }}" ; then
+            echo "Error: Locale '$LOCALE' does not match the required format '[a-z]{2}-[A-Z]{2}'!"
             exit 1
           fi
         env:
